### ISSUE TITLE
IMPORTANT! Editing groups and events.

### ISSUE THREAD

**Issue by Kessaye** [SEM1INFOENS/multiplanner#107]
When creating transactions in the group, then editing the group reducing the members, the transactions saved are not deleted!
This implies that calculating the balance is calculated on these transactions where few old members do not exist in the current edited group. 
This Crashes the server!

**Comment by PierreGtch** [comment]
@Kessaye I think it's normal not to delete the transactions when a user quits a group or an event.
What doesent make sense to me is that the server can crash just because a user is missing (that can happen in many different cases)

For the reslution, we should not suppose that the only persones involved in the transactions are the members of the group

**Comment by Z-ephyr** [comment]
I thought we said one cannot leave the group is their balance is non-zero : I think it is good to keep it this way
If it an administrator want to leaves the group anyway (I think they have the right to), I don't know what we should do... Maybe they should be asked to pay back first anyway (despite being admin)

**Comment by PierreGtch** [comment]
But still, we cannot risk to break an event page if someone find a hack...

**Comment by Z-ephyr** [comment]
We discussed yesterday of putting a try / catch to avoid the break
