### ISSUE TITLE
Editing groups bugs

### ISSUE THREAD

**Issue by Z-ephyr** [SEM1INFOENS/multiplanner#112]
I created a group with four users... Turns out only AnonymousUser is part of it. When I try to edit the group to correct it, I got an error
<img width="1440" alt="screenshot 2019-01-15 at 21 29 57" src="https://user-images.githubusercontent.com/43679368/51208017-be07e080-190c-11e9-8c70-3816a43e4ab4.png">

**Comment by Kessaye** [comment]
Can you please explain a bit more what happened ?

**Comment by Kessaye** [comment]
Locally it works perfectly ...

**Comment by Kessaye** [comment]
Can you please try to recreate the database on the website and re do the test?

**Comment by PierreGtch** [comment]
I recreated the database

Le 16 janv. 2019 16:13, "Kessaye" <notifications@github.com> a écrit :

Can you please try to recreate the database on the website and re do the
test?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SEM1INFOENS/multiplanner/issues/112#issuecomment-454814604>,
or mute the thread

**Comment by Kessaye** [comment]
Ok I will look at later this night (I have an exam in few minutes)

**Comment by Z-ephyr** [comment]
@Kessaye Try with several users and adding every user in the group! That is what breaks it for me

Why can't you use heroku?
