### ISSUE TITLE
Flexible transaction split

### ISSUE THREAD

**Issue by PierreGtch** [SEM1INFOENS/multiplanner#55]
When creating a transaction it should be possible to specify theamount that goes to each beneficiary. 

By  default, the total amount is distributed evenly among beneficiaries, which should yield the same behaviour as in phase 1

**Comment by kameronton** [comment]
I would like to do it

**Comment by kameronton** [comment]
Who wants to help me with the backend part?

**Comment by PierreGtch** [comment]
> Who wants to help me with the backend part?

I can help you!

**Comment by PierreGtch** [comment]
@kameronton I created a branch with a new model for splittable transactions

**Comment by kameronton** [comment]
@PierreGtch , thanks!

I have not succeed with that "range" split form, so I am implementing simple text fields with validation

**Comment by PierreGtch** [comment]
ok :sad: good luck !

**Comment by Kessaye** [comment]
Hello,
I finished the multiple currency issue BUT as usual there are some problems:
* Since the transaction split isn't 100% done yet, I have prefered (after long time of thinking and trying) not to touch this part. So I ran the balance and resolution algorithm with the multiple currency on the transaction done when everyone is evenly paid.
* I tried to get off the Currency in the form part of transaction_details.html , but I couldn't figure out how to do it while still being able to chose the amount. (We do not want to be able to say that we made a transaction in euros (in group_number.html) then in transaction_details.html to change the currency for each person (and to calculate the sum with different currencies)... I hope I was a bit clear) 
* Finally, the problem above causes that when displaying in the group_number the balance, the balance is well calculated but the currency next to it is not correct (Not a big problem for the moment).

-- Finally I will unfortunately not be able to work tomorrow on this, thus if you solved it try to apply the resolution algorithm on the new splitted-transactions (CAREFUL the balance function takes the group as an argument and not the list of transactions (splitted-transactions)!)
